blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/<pk>', views.post_detail, name='post_detail'),
    path('posts/category/<str:category>', views.post_list, name='post_list_category'),
    path('posts/<pk>/comment', views.post_comment, name='post_comment'),
    path('ticket', views.ticket, name='ticket'),
    path('search/', views.search_post, name='search_post'),
    path('profile/', views.profile, name='profile'),
    path('profile/detail/<str:username>/', views.profile_detail, name='profile_detail'),
    path('profile/createpost', views.create_post, name='createpost'),
    path('profile/createpost/<pk>', views.edit_post, name='edit_post'),
    path('profile/delete_image/<image_id>', views.delete_image, name='delete_image'),
    path('profile/delete_post/<pk>', views.delete_post, name='delete_post'),
    # path('login', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name='password-change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password-change-done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password-reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password-reset/complete'), name='password-reset-confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('register/',views.register, name='register'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
]

djangoProject2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog")),
    path('', lambda request: HttpResponseRedirect('/blog/')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment, Post, User, Profile


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('انتقاد', 'انتقاد'),
        ('پیشنهاد', 'پیشنهاد'),
        ('گزارش', 'گزارش')
    )
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)
    message = forms.CharField(widget=forms.Textarea, max_length=1000, required=True)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("مقداری که وارد کردید عدد نیست !")
            else:
                if len(str(phone)) == 11:
                    return phone
                else:
                    raise forms.ValidationError("شماره تلفن باید 11 رقم باشد !")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'text']

    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError('نام کوتاه است !')
            else:
                return name

    def clean_text(self):
        text = self.cleaned_data['text']
        if text:
            if len(text) > 5000:
                raise forms.ValidationError('کامنت شما بیشتر از 5000 کاراکتر است !')
            else:
                return text


class SearchForm(forms.Form):
    query = forms.CharField()


class PostForm(forms.ModelForm):
    image1 = forms.ImageField(label='تصویر اول')
    image2 = forms.ImageField(label='تصویر دوم')

    class Meta:
        model = Post
        fields = ["title", "description", "reading_time", "category"]


# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=250, required=True)
#     password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput, label='رمز عبور')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label='تکرار رمز عبور')

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    def clean_password2(self):
        cd = self.cleaned_data
        password = cd.get('password')
        password2 = cd.get('password2')
        if password and password2 and password != password2:
            raise forms.ValidationError('پسورد ها مطابقت ندارد!')
        return password2


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'job', 'bio', 'photo']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.db.models import Q
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request, "blog/index.html")


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
        'category': category,

    }
    return render(request, 'blog/list.html', context)


# class PostListView(ListView):
#     paginate_by = 3
#     template_name = 'blog/list.html'
#     queryset = Post.published.all()
#     context_object_name = 'posts'


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    form = CommentForm()
    comments = post.comments.filter(active=True)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'blog/detail.html', context)


# class PostDetailView(DetailView):
#     model = Post
#     template_name = 'blog/detail.html'


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket_obj = Ticket.objects.create()
            cd = form.cleaned_data
            ticket_obj.email = cd['email']
            ticket_obj.phone = cd['phone']
            ticket_obj.name = cd['name']
            ticket_obj.message = cd['message']
            ticket_obj.subject = cd['subject']
            ticket_obj.save()
            return redirect('blog:ticket')
    else:
        form = TicketForm()
    return render(request, 'form/ticket.html', {'form': form})


@require_POST
def post_comment(request, pk):
    post = get_object_or_404(Post, pk=pk, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        messages.success(request, 'کامنت شما با موفقیت ثبت شد')
        return redirect('blog:post_detail', pk=pk)
    context = {
        'post': post,
        'form': form,
        'comment': comment,
    }
    return render(request, "form/comment.html", context)


def search_post(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)).filter(
                similarity__gt=0.1)
            results1 = Post.published.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1)
            results = (results2 | results1).order_by('-similarity')
    context = {
        'query': query,
        'results': results
    }

    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    user = request.user
    profile_img = user.profile.photo.url
    posts = Post.published.filter(author=user)
    author = user.username
    context = {
        'posts': posts,
        'profile_img': profile_img,
        'author': author
    }
    return render(request, 'blog/profile.html', context)


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = PostForm()
    return render(request, 'form/createpost.html', {'form': form})


@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:profile')
    return render(request, 'form/delete_post.html', {'post': post})


@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')


@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = PostForm(instance=post)
    return render(request, 'form/edit_post.html', {'form': form, 'post': post})


# def user_login(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('blog:profile')
#                 else:
#                     return HttpResponse('your account is disabled')
#             else:
#                 return HttpResponse('your password or username is wrong')
#     else:
#         form = LoginForm()
#     return render(request, 'form/login.html', {'form':form})

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Profile.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = ProfileEditForm(request.POST, files=request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    return render(request, 'registration/edit_profile.html', context)


def profile_detail(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    posts = Post.published.filter(author=user)
    context = {
        'user': user,
        'profile': profile,
        'posts': posts,
    }
    return render(request, 'blog/profile_detail.html', context)

blog/templates/partials/footer.html
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/footerstyle.css' %}" />
{% endblock %}
<footer>
      <div class="content-footer">
        <div class="resturant">
          <img src="{% static 'images/telegram_logo_circle_icon_134012.png' %}" class="res logo-sub-footer" alt="">
          <p>آریرانگلند</p>
        </div>
        <div class="contact-us">
          <img src="{% static 'images/undraw_social_influencer_re_beim.svg' %}" class="res chef-footer" alt="">
          <div class="social-icons">
            <a href="https://www.tiktok.com/"><i class="fa-brands fa-tiktok"></i></a>
            <a href="https://discord.com/"><i class="fa-brands fa-discord"></i></a>
            <a href="https://www.youtube.com/"><i class="fa-brands fa-youtube"></i></a>
            <a href="https://my.telegram.org/"><i class="fa-brands fa-telegram"></i></a>
          </div>
          <div class="location">
            <p><i class="fa-solid fa-location-dot"></i>مشهد ، میدان فهمیده ، فرامرز عباسی 54</p>
            <p><i class="fa-solid fa-location-dot"></i>تهران ، بزرگراه همت غرب به شرق ، خروجی شیخ فضل الله جنوب</p>
          </div>
        </div>
      </div>
    </footer>

blog/templates/partials/header.html
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/headstyle.css' %}" />
    
{% endblock %}
{% block content %}
    <div class="container-fluid">
          <div class="container">
            <div class="row">
              <div class="header-menu col-12 col-xl-12 mt-3">
                <div class="col-7 logo-wrapper">
                  <img src="{% static 'images/telegram_logo_circle_icon_134012.png' %}" class="res" alt="">
                  <a href="{% url 'blog:index' %}">آریرانگلند</a>
                </div>
                <form method="get" action="{% url 'blog:search_post' %}" class="col-3 search-wrapper">
                  <input type="text" placeholder="جستجو" name="query">
                    <button class="search-btn-wrapper" type="submit"><img class="res search-btn" src="{% static 'images/search-svgrepo-com.svg' %}"></button>
                </form>
                <div class="col-1 login-section">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'blog:profile' %}"><p>{{ request.user.first_name|default:request.user.username}}</p></a>
                        <a href="{% url 'blog:profile' %}"><img src="{% static 'images/0f02d8b8-1178-4c83-a3ff-2ec291c76f73.svg' %}" class="res" alt=""></a>
                    {% else %}
                        <a href="{% url 'blog:login' %}">ورود</a>
                        <a href="{% url 'blog:login' %}"><img src="{% static 'images/0f02d8b8-1178-4c83-a3ff-2ec291c76f73.svg' %}" class="res" alt=""></a>
                    {% endif %}
                    
                </div>
                <div class="col-1 menu-section">
                  <span class="material-symbols-outlined open-menu">menu</span>
                </div>
              </div>
            </div>
          </div>
        </div>
    <div class="menu-container hidden">
        <section>
            <div class="head-menu">
                <img src="{% static 'images/close-lg-svgrepo-com.svg' %}" class="menu-pic close res">
            </div>
            <div class="Menu">
                <img src="{% static 'images/telegram_logo_circle_icon_134012.png' %}" class="menu-logo res">
                <ul>
                    <li><a href="{% url 'blog:index' %}">صفحه اصلی</a></li>
                    <li><a href="{% url 'blog:profile' %}">پروفایل</a></li>
                    <li><a href="{% url 'blog:ticket' %}">ثبت تیکت</a></li>
                    <li><a href="{% url 'blog:createpost' %}">ایجاد پست</a></li>
                    <li><a href="{% url 'blog:edit_profile' %}">ادیت پروفایل</a></li>
                </ul>
            </div>
        </section>
    </div>
    <div class="overlay hidden"></div>
    <script>
        const modal = document.querySelector('.menu-container');
        const closeButton = document.querySelector('.close');
        const overlay = document.querySelector('.overlay');
        const openModalButton = document.querySelector('.open-menu');
        
        const closeModal = function() {
            modal.classList.remove('show');
            overlay.classList.remove('show');
            setTimeout(() => {
                modal.classList.add('hidden');
                overlay.classList.add('hidden');
            }, 300);
        };
        
        const openModal = function() {
            modal.classList.remove('hidden');
            overlay.classList.remove('hidden');
            setTimeout(() => {
                modal.classList.add('show');
                overlay.classList.add('show');
            }, 10); // Slight delay to ensure the elements are not hidden
        };
        
        openModalButton.addEventListener('click', openModal);
        closeButton.addEventListener('click', closeModal);
        overlay.addEventListener('click', closeModal);
        
        document.addEventListener('keydown', function(e) {
            if (e.key === 'Escape') {
                if (!modal.classList.contains('hidden')) {
                    closeModal();
                }
            }
        });
    </script>
{% endblock %}

blog/templates/partials/last_posts.html
{% load jformat %}
<div>
    <h2>آخرین پست ها</h2>
    {% for post in lposts %}
        <a href="{{ post.get_absolute_url }}">{{ post.title }} {{ post.publish | jformat:"%Y/%m/%d - %H:%M" }}</a>
        <br>
    {% endfor %}
</div>

blog/templates/partials/pagination.html
<div class="pagination">
    <div class="previous">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">قبلی</a>
        {% endif %}
    </div>
    <p>page {{ page.number }} of {{ page.paginator.num_pages }}</p>
    <div class="next">
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">بعدی</a>
        {% endif %}
    </div>

</div>