blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/<pk>', views.post_detail, name='post_detail'),
    path('posts/category/<str:category>', views.post_list, name='post_list_category'),
    path('posts/<pk>/comment', views.post_comment, name='post_comment'),
    path('ticket', views.ticket, name='ticket'),
    path('search/', views.search_post, name='search_post'),
    path('profile/', views.profile, name='profile'),
    path('profile/detail/<str:username>/', views.profile_detail, name='profile_detail'),
    path('profile/createpost', views.create_post, name='createpost'),
    path('profile/createpost/<pk>', views.edit_post, name='edit_post'),
    path('profile/delete_image/<image_id>', views.delete_image, name='delete_image'),
    path('profile/delete_post/<pk>', views.delete_post, name='delete_post'),
    # path('login', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name='password-change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password-change-done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password-reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password-reset/complete'), name='password-reset-confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('register/',views.register, name='register'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
]

djangoProject2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog")),
    path('', lambda request: HttpResponseRedirect('/blog/')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment, Post, User, Profile


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('انتقاد', 'انتقاد'),
        ('پیشنهاد', 'پیشنهاد'),
        ('گزارش', 'گزارش')
    )
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)
    message = forms.CharField(widget=forms.Textarea, max_length=1000, required=True)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("مقداری که وارد کردید عدد نیست !")
            else:
                if len(str(phone)) == 11:
                    return phone
                else:
                    raise forms.ValidationError("شماره تلفن باید 11 رقم باشد !")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'text']

    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError('نام کوتاه است !')
            else:
                return name

    def clean_text(self):
        text = self.cleaned_data['text']
        if text:
            if len(text) > 5000:
                raise forms.ValidationError('کامنت شما بیشتر از 5000 کاراکتر است !')
            else:
                return text


class SearchForm(forms.Form):
    query = forms.CharField()


class PostForm(forms.ModelForm):
    image1 = forms.ImageField(label='تصویر اول')
    image2 = forms.ImageField(label='تصویر دوم')

    class Meta:
        model = Post
        fields = ["title", "description", "reading_time", "category"]


# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=250, required=True)
#     password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput, label='رمز عبور')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label='تکرار رمز عبور')

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    def clean_password2(self):
        cd = self.cleaned_data
        password = cd.get('password')
        password2 = cd.get('password2')
        if password and password2 and password != password2:
            raise forms.ValidationError('پسورد ها مطابقت ندارد!')
        return password2


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'job', 'bio', 'photo']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.db.models import Q
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request, "blog/index.html")


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
        'category': category,

    }
    return render(request, 'blog/list.html', context)


# class PostListView(ListView):
#     paginate_by = 3
#     template_name = 'blog/list.html'
#     queryset = Post.published.all()
#     context_object_name = 'posts'


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    form = CommentForm()
    comments = post.comments.filter(active=True)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'blog/detail.html', context)


# class PostDetailView(DetailView):
#     model = Post
#     template_name = 'blog/detail.html'


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket_obj = Ticket.objects.create()
            cd = form.cleaned_data
            ticket_obj.email = cd['email']
            ticket_obj.phone = cd['phone']
            ticket_obj.name = cd['name']
            ticket_obj.message = cd['message']
            ticket_obj.subject = cd['subject']
            ticket_obj.save()
            return redirect('blog:ticket')
    else:
        form = TicketForm()
    return render(request, 'form/ticket.html', {'form': form})


@require_POST
def post_comment(request, pk):
    post = get_object_or_404(Post, pk=pk, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        messages.success(request, 'کامنت شما با موفقیت ثبت شد')
        return redirect('blog:post_detail', pk=pk)
    context = {
        'post': post,
        'form': form,
        'comment': comment,
    }
    return render(request, "form/comment.html", context)


def search_post(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)).filter(
                similarity__gt=0.1)
            results1 = Post.published.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1)
            results = (results2 | results1).order_by('-similarity')
    context = {
        'query': query,
        'results': results
    }

    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    user = request.user
    profile_img = user.profile.photo.url
    posts = Post.published.filter(author=user)
    author = user.username
    context = {
        'posts': posts,
        'profile_img': profile_img,
        'author': author
    }
    return render(request, 'blog/profile.html', context)


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = PostForm()
    return render(request, 'form/createpost.html', {'form': form})


@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:profile')
    return render(request, 'form/delete_post.html', {'post': post})


@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')


@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = PostForm(instance=post)
    return render(request, 'form/edit_post.html', {'form': form, 'post': post})


# def user_login(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('blog:profile')
#                 else:
#                     return HttpResponse('your account is disabled')
#             else:
#                 return HttpResponse('your password or username is wrong')
#     else:
#         form = LoginForm()
#     return render(request, 'form/login.html', {'form':form})

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Profile.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = ProfileEditForm(request.POST, files=request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    return render(request, 'registration/edit_profile.html', context)


def profile_detail(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    posts = Post.published.filter(author=user)
    context = {
        'user': user,
        'profile': profile,
        'posts': posts,
    }
    return render(request, 'blog/profile_detail.html', context)

blog/templates/form/comment.html
{% extends 'parent/base.html' %}
{% load static %}
{% load jformat %}
{% block title %}post comment{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/comment-sectionstyle.css' %}">
{% endblock %}
{% block content %}
    {% if comment %}
        <p>کامنت خود را اصلاح کنید !</p>
        <a href="{{ post.get_absolute_url }}">بازگشت</a>
    {% else %}
    <div class="comment-section">
            <form method="post" action="{% url 'blog:post_comment' post.id %}">
            {% csrf_token %}
                <div class="inputbox">
                  <label for="nameid">اسم : </label>
                  <input id="nameid" type="text" name="name" required class="names"
                  {% if form.name.value %}value="{{ form.name.value }}" {% endif %}>
                    {{ form.name.errors }}
                </div>
                <div class="inputbox2">
                  <label for="textarea">کامنت : </label>
                      <textarea id="textarea" name="text"  required class="texts-c">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
                    {{ form.text.errors }}
                </div>
            <input type="submit" value="افزودن کامنت">
            </form>

        </div>
    {% endif %}

{% endblock %}

blog/templates/form/createpost.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}create post{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/createpoststyle.css' %}">
{% endblock %}
{% block content %}
    <div class="post-section">
        <form method="post" enctype="multipart/form-data" class="post-form">
        {% csrf_token %}
            <h3>پست جدید</h3>
            <div class="inputGroup">
              <input id="title" type="text" name="title" required class="title_input"
              {% if form.title.value %}value="{{ form.title.value }}" {% endif %}>
              <label for="title">موضوع : </label>
                {{ form.title.errors }}
            </div>
            <div class="inputGroup">
                <textarea id="textarea" name="description" placeholder="توضیحات : " required class="description_input">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
                {{ form.description.errors }}
            </div>
            <div class="inputGroup">
              <input id="time" type="number" min="1" max="100" name="reading_time" required class="time_input"
                {% if form.reading_time.value %}value="{{ form.reading_time.value }}" {% endif %}>
                <label for="time">زمان مطالعه : </label>
                {{ form.reading_time.errors }}
            </div>
            <div class="inputbox1 inputbox">
             <label for="sub">دسته بندی : </label>
              <select name="category" id="sub" >
                  <option value="انیمه" {% if form.subject.value == "انیمه"%}selected{% endif %}>انیمه</option>
                  <option value="سریال" {% if form.subject.value == "سریال"%}selected{% endif %}>سریال</option>
                  <option value="گردشگری" {% if form.subject.value == "گردشگری"%}selected{% endif %}>گردشگری</option>
                  <option value="برنامه نویسی" {% if form.subject.value == "برنامه نویسی"%}selected{% endif %}>برنامه نویسی</option>
                  <option value="آشپزی" {% if form.subject.value == "آشپزی"%}selected{% endif %}>آشپزی</option>
                  <option value="مدلینگ" {% if form.subject.value == "مدلینگ"%}selected{% endif %}>مدلینگ</option>
                  <option value="طراحی" {% if form.subject.value == "طراحی"%}selected{% endif %}>طراحی</option>
                  <option value="متفرقه" {% if form.subject.value == "متفرقه"%}selected{% endif %}>متفرقه</option>
              </select>
                {{ form.subject.errors }}
            </div>
            <div class="input-box">
              <label for="pic1">عکس اول : </label>
              <input id="pic1" type="file" name="image1" class="image_input">
              <button type="button" class="submit" onclick="document.getElementById('pic1').click();">افزودن عکس</button>
              <span id="file-name1" class="file-name" style="margin-right: 10px"></span>
              {{ form.image1.errors }}
            </div>
            <div class="input-box">
              <label for="pic2">عکس دوم : </label>
              <input id="pic2" type="file" name="image2" class="image_input">
              <button type="button" class="submit" onclick="document.getElementById('pic2').click();">افزودن عکس</button>
              <span id="file-name2" class="file-name" style="margin-right: 10px"></span>
              {{ form.image2.errors }}
            </div>
        <input type="submit" value="افزودن پست" class="confirm">
        </form>
    </div>
{% endblock %}

blog/templates/form/delete_post.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}delete post{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/delete-post-style.css' %}">
{% endblock %}
{% block content %}
    <form method="post" class="del-form">
        {% csrf_token %}
        <p> آیا از حذف پست <span> "{{ post.title }}" </span>مطمئن هستید ؟ </p>
        <div class="btn-wrapper">
            <a href="{% url 'blog:profile' %}">لغو</a>
            <button type="submit">تایید</button>
        </div>

    </form>
    <br>
    <br>
    <br>
    <br>    <br>
    <br>
    <br>
    <br>

{% endblock %}

blog/templates/form/edit_post.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}create post{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/edit-post-style.css' %}">
{% endblock %}
{% block content %}
    <div class="post-section">
        <form method="post" enctype="multipart/form-data" class="post-form">
        {% csrf_token %}
            <h3>ادیت پست</h3>
            <div class="inputGroup">
              <input id="title" type="text" name="title" required class="title_input"
              {% if form.title.value %}value="{{ form.title.value }}" {% endif %}>
              <label for="title">موضوع : </label>
                {{ form.title.errors }}
            </div>
            <div class="inputGroup">
                <textarea id="textarea" name="description" placeholder="توضیحات : " required class="description_input">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
                {{ form.description.errors }}
            </div>
            <div class="inputGroup">
              <input id="time" type="number" min="1" max="100" name="reading_time" required class="time_input"
                {% if form.reading_time.value %}value="{{ form.reading_time.value }}" {% endif %}>
                <label for="time">زمان مطالعه : </label>
                {{ form.reading_time.errors }}
            </div>
            <div class="input-box">
              <label for="pic1">عکس اول : </label>
              <input id="pic1" type="file" name="image1" class="image_input">
              <button type="button" class="submit" onclick="document.getElementById('pic1').click();">افزودن عکس</button>
              <span id="file-name1" class="file-name" style="margin-right: 10px"></span>
              {{ form.image1.errors }}
            </div>
            <div class="input-box">
              <label for="pic2">عکس دوم : </label>
              <input id="pic2" type="file" name="image2" class="image_input">
              <button type="button" class="submit" onclick="document.getElementById('pic2').click();">افزودن عکس</button>
              <span id="file-name2" class="file-name" style="margin-right: 10px"></span>
              {{ form.image2.errors }}
            </div>
            <div class="inputbox1 inputbox">
             <label for="sub">دسته بندی : </label>
              <select name="category" id="sub" >
                  <option value="انیمه" {% if form.subject.value == "انیمه"%}selected{% endif %}>انیمه</option>
                  <option value="سریال" {% if form.subject.value == "سریال"%}selected{% endif %}>سریال</option>
                  <option value="گردشگری" {% if form.subject.value == "گردشگری"%}selected{% endif %}>گردشگری</option>
                  <option value="برنامه نویسی" {% if form.subject.value == "برنامه نویسی"%}selected{% endif %}>برنامه نویسی</option>
                  <option value="آشپزی" {% if form.subject.value == "آشپزی"%}selected{% endif %}>آشپزی</option>
                  <option value="مدلینگ" {% if form.subject.value == "مدلینگ"%}selected{% endif %}>مدلینگ</option>
                  <option value="طراحی" {% if form.subject.value == "طراحی"%}selected{% endif %}>طراحی</option>
                  <option value="متفرقه" {% if form.subject.value == "متفرقه"%}selected{% endif %}>متفرقه</option>
              </select>
                {{ form.subject.errors }}
            </div>
            <div class="img-container">
                {% for img in post.images.all %}
                    <div class="del-wrapper">
                        <img src="{{ img.image_file.url }}">
                        <a href="{% url 'blog:delete_image' img.id %}">حذف تصویر</a>
                    </div>
                {% endfor %}
            </div>
        <input type="submit" value="اعمال تغییرات" class="confirm">
        </form>
    </div>
{% endblock %}

blog/templates/form/ticket.html
{% extends 'parent/base.html' %}
{% load static %}
{% block head %}<link rel="stylesheet" href="{% static 'css/formstyle.css' %}" />{% endblock %}
{% block title %}ticket form{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
            <div class="form-value">
                <div class="form-box">
                      <form method="post">
                          <h2>ارتباط با ما</h2>
                          <div class="welcome">
                              <p class="first-p">سلام!</p>
                              <p>تیکت خود را با پر کردن فرم زیر ارسال کنید </p>
                          </div>

                          <div class="inputbox">
                              <label for="nameid">اسم : </label>
                              <input id="nameid" type="text" name="name" required class="names"
                              {% if form.name.value %}value="{{ form.name.value }}" {% endif %}>
                                {{ form.name.errors }}
                          </div>
                          <div class="inputbox">
                              <label for="emailid">ایمیل : </label>
                              <input id="emailid" type="email" name="email" required class="emails"
                              {% if form.email.value %}value="{{ form.email.value }}" {% endif %}>
                              {{ form.email.errors }}
                          </div>
                          <div class="inputbox">
                              <label for="">شماره تلفن : </label>
                              <input type="text" name="phone"  required class="phones"
                              {% if form.phone.value %}value="{{ form.phone.value }}" {% endif %}>
                                {{ form.phone.errors }}
                          </div>
                          <div class="inputbox inputbox1">
                              <label for="sub">موضوع : </label>
                              <select name="subject" id="sub" >
                                  <option value="انتقاد" {% if form.subject.value == "انتقاد"%}selected{% endif %}>انتقاد</option>
                                  <option value="پیشنهاد" {% if form.subject.value == "یشنهاد"%}selected{% endif %}>پیشنهاد</option>
                                  <option value="گزارش" {% if form.subject.value == "گزارش"%}selected{% endif %}>گزارش</option>
                              </select>
                                {{ form.subject.errors }}
                          </div>
                          <div class="inputbox2">
                              <label for="textarea">پیام : </label>
                                  <textarea id="textarea" name="message"  required class="messages">{% if form.message.value %}{{ form.message.value }}{% endif %}</textarea>
                                {{ form.message.errors }}
                          </div>
{#                          <div class="error-section">#}
{#                            {% if form.errors %}#}
{#                                {% for field in form %}#}
{#                                    {% if field.errors %}#}
{#                                        {% for error in field.errors %}#}
{#                                           {{ error }}#}
{#                                        {% endfor %}#}
{#                                    {% endif %}#}
{#                                {% endfor %}#}
{#                            {% endif %}#}
{#                          {% if form.non_field_errors %}#}
{#                              {{ form.non_field_errors }}#}
{#                          {% endif %}#}
{#                          </div>#}
                          <button>ثبت</button>

                      </form>
                </div>
            </div>
    </form>

{% endblock %}