blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/<pk>', views.post_detail, name='post_detail'),
    path('posts/category/<str:category>', views.post_list, name='post_list_category'),
    path('posts/<pk>/comment', views.post_comment, name='post_comment'),
    path('ticket', views.ticket, name='ticket'),
    path('search/', views.search_post, name='search_post'),
    path('profile/', views.profile, name='profile'),
    path('profile/detail/<str:username>/', views.profile_detail, name='profile_detail'),
    path('profile/createpost', views.create_post, name='createpost'),
    path('profile/createpost/<pk>', views.edit_post, name='edit_post'),
    path('profile/delete_image/<image_id>', views.delete_image, name='delete_image'),
    path('profile/delete_post/<pk>', views.delete_post, name='delete_post'),
    # path('login', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name='password-change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password-change-done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password-reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password-reset/complete'), name='password-reset-confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('register/',views.register, name='register'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
]

djangoProject2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog")),
    path('', lambda request: HttpResponseRedirect('/blog/')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment, Post, User, Profile


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('انتقاد', 'انتقاد'),
        ('پیشنهاد', 'پیشنهاد'),
        ('گزارش', 'گزارش')
    )
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)
    message = forms.CharField(widget=forms.Textarea, max_length=1000, required=True)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("مقداری که وارد کردید عدد نیست !")
            else:
                if len(str(phone)) == 11:
                    return phone
                else:
                    raise forms.ValidationError("شماره تلفن باید 11 رقم باشد !")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'text']

    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError('نام کوتاه است !')
            else:
                return name

    def clean_text(self):
        text = self.cleaned_data['text']
        if text:
            if len(text) > 5000:
                raise forms.ValidationError('کامنت شما بیشتر از 5000 کاراکتر است !')
            else:
                return text


class SearchForm(forms.Form):
    query = forms.CharField()


class PostForm(forms.ModelForm):
    image1 = forms.ImageField(label='تصویر اول')
    image2 = forms.ImageField(label='تصویر دوم')

    class Meta:
        model = Post
        fields = ["title", "description", "reading_time", "category"]


# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=250, required=True)
#     password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput, label='رمز عبور')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label='تکرار رمز عبور')

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    def clean_password2(self):
        cd = self.cleaned_data
        password = cd.get('password')
        password2 = cd.get('password2')
        if password and password2 and password != password2:
            raise forms.ValidationError('پسورد ها مطابقت ندارد!')
        return password2


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'job', 'bio', 'photo']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.db.models import Q
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request, "blog/index.html")


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
        'category': category,

    }
    return render(request, 'blog/list.html', context)


# class PostListView(ListView):
#     paginate_by = 3
#     template_name = 'blog/list.html'
#     queryset = Post.published.all()
#     context_object_name = 'posts'


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    form = CommentForm()
    comments = post.comments.filter(active=True)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'blog/detail.html', context)


# class PostDetailView(DetailView):
#     model = Post
#     template_name = 'blog/detail.html'


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket_obj = Ticket.objects.create()
            cd = form.cleaned_data
            ticket_obj.email = cd['email']
            ticket_obj.phone = cd['phone']
            ticket_obj.name = cd['name']
            ticket_obj.message = cd['message']
            ticket_obj.subject = cd['subject']
            ticket_obj.save()
            return redirect('blog:ticket')
    else:
        form = TicketForm()
    return render(request, 'form/ticket.html', {'form': form})


@require_POST
def post_comment(request, pk):
    post = get_object_or_404(Post, pk=pk, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        messages.success(request, 'کامنت شما با موفقیت ثبت شد')
        return redirect('blog:post_detail', pk=pk)
    context = {
        'post': post,
        'form': form,
        'comment': comment,
    }
    return render(request, "form/comment.html", context)


def search_post(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)).filter(
                similarity__gt=0.1)
            results1 = Post.published.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1)
            results = (results2 | results1).order_by('-similarity')
    context = {
        'query': query,
        'results': results
    }

    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    user = request.user
    profile_img = user.profile.photo.url
    posts = Post.published.filter(author=user)
    author = user.username
    context = {
        'posts': posts,
        'profile_img': profile_img,
        'author': author
    }
    return render(request, 'blog/profile.html', context)


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = PostForm()
    return render(request, 'form/createpost.html', {'form': form})


@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:profile')
    return render(request, 'form/delete_post.html', {'post': post})


@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')


@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = PostForm(instance=post)
    return render(request, 'form/edit_post.html', {'form': form, 'post': post})


# def user_login(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('blog:profile')
#                 else:
#                     return HttpResponse('your account is disabled')
#             else:
#                 return HttpResponse('your password or username is wrong')
#     else:
#         form = LoginForm()
#     return render(request, 'form/login.html', {'form':form})

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Profile.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = ProfileEditForm(request.POST, files=request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    return render(request, 'registration/edit_profile.html', context)


def profile_detail(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    posts = Post.published.filter(author=user)
    context = {
        'user': user,
        'profile': profile,
        'posts': posts,
    }
    return render(request, 'blog/profile_detail.html', context)

blog/templates/blog/detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% load jformat %}
{% load blog_tags %}
{% block title %}post detail{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/comment-sectionstyle.css' %}">
{% endblock %}
{% block content %}

    <div class="container">
        <div class="row post_container">
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for img in post.images.all %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <img src="{{ img.image_file.url }}" class="d-block w-100 detail-post-image res" alt="{{ img.title }}">
                        </div>
                    {% endfor %}
                 </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
            <h4 class="title_detail">{{ post.title }}</h4>
            <h5>نویسنده :  {{ post.author }}</h5>
            <p>{{ post.description | markdown }}</p>
            <hr>
            <span>{{ post.publish | jformat:"%Y/%m/%d - %H:%M" }}</span>
        </div>
        <div class="comment-section">
            <form method="post" action="{% url 'blog:post_comment' post.id %}">
            {% csrf_token %}
                <div class="inputbox">
                  <label for="nameid">اسم : </label>
                  <input id="nameid" type="text" name="name" required class="names"
                  {% if form.name.value %}value="{{ form.name.value }}" {% endif %}>
                    {{ form.name.errors }}
                </div>
                <div class="inputbox2">
                  <label for="textarea">کامنت : </label>
                      <textarea id="textarea" name="text"  required class="texts-c">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
                    {{ form.text.errors }}
                </div>
            <input type="submit" value="افزودن کامنت">
            </form>
            <div class="num-comment">
                {% with comments.count as cm_count %}
                <span>تعداد کامنت : </span>{{ cm_count }}
                {% endwith %}
            </div>
            <br>
            <div class="comment-container">
                {% for cm in comments %}
                    <div class="comment">
                        <p class="comment-name">{{ cm.name }}</p>
                        <br>
                        {{ cm.text|linebreaks }}
                    </div>
                    {% empty %}
                    <p>کامنتی وجود ندارد</p>
                {% endfor %}
            </div>


        </div>


    </div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'parent/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/index-style.css' %}" />
{% endblock %}
{% block title %}Arirangland{% endblock %}
{% load blog_tags %}
{% load jformat %}
{% block content %}
    <div class="container">
        <div class="Header-wrapper">
            <img src="{% static 'images/group-young-adult-friends-using-smartphones-subway.jpg' %}" class="Header-img res">
            <div class="Header-content">
                <h2>با آریرانگلند به دوستات نزدیک تر شو</h2>
                <a href="{% url 'blog:post_list' %}" class="Header-btn">دیدن پست ها</a>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/list.html
{% extends 'parent/base.html' %}
{% block title %}post list{% endblock %}
{% load blog_tags %}
{% load static %}
{% load jformat %}
{% block content %}
    <div class="container d-flex flex-row">
        <div class="row d-flex flex-column align-items-center justify-content-start center-content px-5">
            {% if category %}
                <h4 class="text_head"> لیست پست های {{ category }} </h4>
            {% else %}
                <h4 class="text_head">لیست پست ها</h4>
            {% endif %}
            {% for post in posts %}
                <div class="post col-7">
                    <a  href="{{ post.get_absolute_url }}" class="post-content">
                    <img src="{{ post.images.first.image_file.url }}" class="list-post-image res" alt="{{ post.images.first.title }}">
                    <div class="content-list">
                        {% if post.author.profile.photo %}
                            <a href="{% url 'blog:profile_detail' username=post.author.username %}" class="title_post mb-2"><img src="{{ post.author.profile.photo.url }}">{{ post.author }}</a>
                        {% else %}
                            <a href="{% url 'blog:profile_detail' username=post.author.username %}" class="title_post mb-2"><img src="{% static 'images/profile.png' %}">{{ post.author }}</a>
                        {% endif %}
                        
                        <span >{{ post.publish | jformat:"%Y/%m/%d - %H:%M" }}</span>
                    
                        <p>{{ post.description | truncatewords:10 }}</p>
                        
                        
                        <a class="btn-confirm" href="{{ post.get_absolute_url }}">بیشتر</a>
                        
                    </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <aside class="left-aside">
            <div class="category">
                <h4>دسته بندی</h4>
                <a href="{% url 'blog:post_list_category' 'انیمه' %}">انیمه</a>
                <a href="{% url 'blog:post_list_category' 'سریال' %}">سریال</a>
                <a href="{% url 'blog:post_list_category' 'گردشگری' %}">گردشگری</a>
                <a href="{% url 'blog:post_list_category' 'برنامه نویسی' %}">برنامه نویسی</a>
                <a href="{% url 'blog:post_list_category' 'آشپزی' %}">آشپزی</a>
                <a href="{% url 'blog:post_list_category' 'مدلینگ' %}">مدلینگ</a>
                <a href="{% url 'blog:post_list_category' 'طراحی' %}">طراحی</a>
                <a href="{% url 'blog:post_list_category' 'متفرقه' %}">متفرقه</a>
            </div>
            <div class="popular-posts">
                <h4>محبوب ترین پست ها</h4>
                {% most_popular_posts as mpp %}
                {% for post in mpp %}
                    <a href="{{ post.get_absolute_url }}" class="popular-post"><img src="{{ post.images.first.image_file.url }}" class="res">{{ post.title }}</a>
                    <br>
                {% endfor %}
            </div>
        </aside>
    </div>
    <br>
    <br>
    <br>
    <br>
    {% include 'partials/pagination.html' with page=posts %}
{#    {% include 'partials/pagination.html' with page=page_obj %}#}

{% endblock %}

blog/templates/blog/profile.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}profile{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/profilestyle.css' %}">
{% endblock %}
{% block content %}
    <div class="head"></div>
    <a href="{% url 'blog:createpost' %}" class="create-btn">ایجاد پست</a>
    <form method="post" action="{% url 'blog:logout' %}">
        {% csrf_token %}
        <button type="submit" class="logout-btn">خروج از حساب</button>
    </form>
    <form method="post" action="{% url 'blog:password-change' %}">
        {% csrf_token %}
        <button type="submit" class="change-pass-btn">تغییر پسورد</button>
    </form>
    <form method="post" action="{% url 'blog:edit_profile' %}">
        {% csrf_token %}
        <button type="submit" class="edit-profile-btn">ادیت پروفایل</button>
    </form>
    <h4><img src="{{ profile_img }}" class="res profile-img"> <span>{{ author }}</span></h4>
    <table>
        {% for post in posts %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td class="image-wrapper"><img src="{{ post.images.first.image_file.url }}" class="res"></td>
                <td>{{ post.title }}</td>
                <td class="see-btn"><a href="{{ post.get_absolute_url }}">دیدن</a></td>
                <td class="edit-btn"><a href="{% url 'blog:edit_post' post.id %}">ویرایش</a></td>
                <td><a href="{% url 'blog:delete_post' post.id %}" type="button" class="delbtn" >حذف</a></td>
            </tr>
        {% empty %}
            <h3>پستی وجود ندارد</h3>
        {% endfor %}
        
    </table>
    <br>
    <br>
    <br>
    <br>

{% endblock %}

blog/templates/blog/profile_detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% load jformat %}
{% block title %}پروفایل{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/profile_detail.css' %}">
{% endblock %}
{% block content %}
    <div class="container d-flex justify-content-center">
        <section class="profile_detail">
            {% if profile.photo %}
                <img src="{{ profile.photo.url }}" alt="Profile Image" class="profile-img">
            {% else %}
                <img src="{% static 'images/profile.png' %}" alt="Default Profile Image" class="profile-img">
            {% endif %}
            <h2>{{ user.username }}</h2>
            <p><span>بیو:</span> {{ profile.bio }}</p>
            <p><span>شغل:</span> {{ profile.job }}</p>
            <p><span>تاریخ تولد:</span> {{ profile.date_of_birth | jformat:"%Y/%m/%d" }}</p>
        </section>
    </div>
    <div class="container">
        <div class="post-section">
            <h3>POSTS</h3>
            <section>
                {% for post in posts %}
                    <div class="flip-card">
                        <div class="flip-card-inner">
                            <div class="flip-card-front">
                                <img src="{{ post.images.first.image_file.url }}">
                            </div>
                            <div class="flip-card-back">
                                <span>{{ post.title }}</span>
                                <span>{{ post.created | jformat:"%Y/%m/%d - %H:%M"}}</span>
                                <span><a href="{{ post.get_absolute_url }}">مشاهده</a></span>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <h3>پستی وجود ندارد</h3>
                {% endfor %}
            </section>
        </div>
    </div>
    
{% endblock %}

blog/templates/blog/search.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}post search{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/searchstyle.css' %}">
{% endblock %}
{% block content %}
    {% if query %}
        <p class="title"> نتایج جستجو برای : {{ query }} </p>
    {% endif %}
    {% for post in results %}
        <div class="search-section">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            <p>{{ post.description }}</p>
        </div>
    {% empty %}
        <span class="search-not-found">نتیجه ای یافت نشد !!</span>
        <br><br><br><br><br><br><br><br><br><br>
    {% endfor %}

{% endblock %}